library(MASS)
library(plyr) 
library(ggplot2)
library(knitr)
library(kableExtra)
library(GGally)
library(rpart)
library(rpart.plot)
library(randomForest)
library(caTools)
library(caret)
DecisionsDF = read.csv('D:/uni/DECISION MODELS/Exercise 4 - CART and Random Forest-20180326/Stevens.csv')
str(DecisionsDF)
summary(DecisionsDF)
set.seed(100)
spl = sample.split(DecisionsDF$Reverse, SplitRatio = 0.70)
DecisionsDFTrain = subset(DecisionsDF, spl = TRUE)
DecisionsDFTest = subset(DecisionsDF, spl = FALSE)
DecisionsDFTrain$Reverse = as.factor(DecisionsDFTrain$Reverse)
DecisionDFTree = rpart(formula = Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, method = 'class', data = DecisionsDFTrain, control = rpart.control(minbucket = 15))
printcp(DecisionDFTree)
DecisionDFTree$variable.importance
plot(DecisionDFTree)
text(DecisionDFTree)
#plot with rattle
library(rattle)
fancyRpartPlot(DecisionDFTree, palettes=c('Greys', 'Oranges'), sub = 'Fancy rpart plot')
predictedDecisions <- predict(DecisionDFTree,DecisionsDF,type="class")
confusionMatrix(predictedDecisions, DecisionsDF$Reverse)
#TRY TO IMPROVE THE MODEL by validating on training set
set.seed(100)
spl = sample.split(DecisionsDFTrain$Reverse, SplitRatio = 0.5)
DecisionsDFValidateTrain = subset(DecisionsDFTrain, spl == TRUE)
DecisionsDFValidateTest = subset(DecisionsDFTrain, spl == FALSE)
DecisionsDFTree1 = rpart(formula = Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, method = 'class', data = DecisionsDFValidateTrain, minbucket = 5)
DecisionsDFTree2 = rpart(formula = Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, method = 'class', data = DecisionsDFValidateTrain, minbucket = 15)
DecisionsDFTree3 = rpart(formula = Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, method = 'class', data = DecisionsDFValidateTrain, minbucket = 25)
#predict on validating test set
DecisionsDFPredict1 = predict(DecisionsDFTree1, newdata = DecisionsDFValidateTest, type = 'class')
DecisionsDFPredict2 = predict(DecisionsDFTree2, newdata = DecisionsDFValidateTest, type = 'class')
DecisionsDFPredict3 = predict(DecisionsDFTree3, newdata = DecisionsDFValidateTest, type = 'class')
confusionMatrix(DecisionsDFPredict1, DecisionsDFValidateTest$Reverse)
confusionMatrix(DecisionsDFPredict2, DecisionsDFValidateTest$Reverse)
confusionMatrix(DecisionsDFPredict3, DecisionsDFValidateTest$Reverse)
DecisionsDFTreeFinal = rpart(formula = Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, method="class", data=DecisionsDFTrain, minbucket=15)
DecisionsDFPredictTest = predict(DecisionsDFTreeFinal, newdata=DecisionsDFTest, type="class")
confusionMatrix(DecisionsDFPredictTest, DecisionsDFTest$Reverse)
